### ISSUE TITLE
Styling issues

### ISSUE THREAD

**Issue by hypha** [EuroPython/website#224]
- [x] A: Hyperlinks with the anchor element has no underline or primary colour styling. 
- [x] B: Lists using MD (- or *) doesn't show bullets; using `<li>` changes font size. Currently amended main.css [here](https://github.com/EuroPython/website/pull/225/files#diff-7421d78623e713232310ca42d646b242853cb9bab6e64e420fc8a94ce02ccd20) 
- [x] C: title's # doesn't get hidden on mobile
- [x] D: ` <ButtonWithTitle>` and `<ButtonLink>` -  need a linebreak after the button. The title currently applies h3, which looks a bit big.
- [x] E: `<img>` needs a linkebreak after the image.
- [x] F: p.large styling doesn't exist. `<p>` styling is also different from text without the tag.  
- [x] G: I think the sponsor page width needs to be wider to fit the tiers. 
- [ ] H: with the font size bigger than 2022, I am not sure if it makes sense to increase the overall width for the text. 
Edit: According to Sebastiaan, the general recommendation for text length is between 50-80 characters per line for readability. We might want to consider what an appropriate width is. 
- [x] I: the bullet point points to the middle of several lines. This looks very confusing when it is nested. e.g. the following renders as seen in screenshot
![image](https://user-images.githubusercontent.com/6319134/234101609-f3e47f5e-a3a2-4294-9f80-3cbd7930d5b1.png)
* Fruit
  * Apple

**Comment by patrick91** [comment]
hyperlinks fixed, there's no need to use `<a href="">` anymore 😊

**Comment by SebastiaanZ** [comment]
I briefly looked into sources on the effect of line length on readability for digital screens. Unfortunately, I don't have access to most full-text articles anymore.

There seem to be a couple of different approaches to this question, though. Those approaches include measuring a speed/comprehension trade-off, testing for scanning/visual search in text, and measuring subjective preferences for line lengths. The problem is that there seem to be different answers based on what is measured.

In general, I've read that:

- Longer line lengths are better for quick scanning, as you have to scroll less and make fewer line jumps. 
- Medium line lengths (often defined as somewhere between 50 - 80 characters per line) are better for accuracy 
- Medium line lengths are preferred by most participants.

Here ar a few sources:

### Dyson, M.C., & Kipping, G.J. (1998). The Effects of Line Length and Method of Movement on Patterns of Reading from Screen. Visible Language, 32.

This study comes to two different conclusions:

- People read faster at long line lengths (defined as 100 characters per line) compared to shorter line lengths while reading comprehension stayed pretty much constant over line lengths
- People subjectively preferred reading at medium line lengths (with the most preferred length being 55 characters per line)

In the discussion, they suggest that you should be careful applying principles from printed text to text on screens.

### Ling, J., & Van Schaik, P. (2006). The influence of font type and line length on visual search and information retrieval in web pages. International journal of human-computer studies, 64(5), 395-404.

This study comes to the conclusion that longer lines allow for faster scanning of a text for specific terms, but when it comes to processing the information and recalling it later, they found an optimal line length of 70 characters per line. In addition, the subjective preference was for shorter line lengths (55 - 70 characters per line), with a strong effect size in their first experiment and a small-to-medium effect size in their second experiment.

Their main design recommendation relevant to our discussion is:

> Given a choice between using long (85–100) and short line lengths (55–70), designers should opt for the latter, because although scanning web pages is also a major activity when finding information on websites (Kitajima et al., 2000), the majority of textual web content is presented to be read rather than skimmed. (page 403)

### Baymard Institute

This is a private institute from Denmark, but they do a lot of applied UX research. They have an [article on line length](https://baymard.com/blog/line-length-readability) that recommends 50-75 characters per line.

### Wikipedia

Wikipedia does not provide a clear guideline in terms of line length for electronic text, but also states that shorter line lengths are better for accuracy, while longer line length have benefits for scanning tasks. See https://en.wikipedia.org/wiki/Line_length.

**Comment by hypha** [comment]
@patrick91 Added issue I that is creating a bit of a problem.
