### ISSUE TITLE
2023 sponsor tiers are a bit mangled

### ISSUE THREAD

**Issue by hypha** [EuroPython/website#535]
At some point, the 2023 sponsor page became less neat :)
![image](https://github.com/EuroPython/website/assets/6319134/826e8611-8f45-4e00-9ce6-be003c70b36c)

**Comment by egeakman** [comment]
@hypha Should we close this as this is mostly fixed in 2024 website? Unless we want to backport this to [``archive/2023``](https://github.com/EuroPython/website/tree/archive/2023)?

This is how it looks currently:
![image](https://github.com/EuroPython/website/assets/75242929/3ade68d7-3dd0-4014-8869-e5b5020bc077)

**Comment by hypha** [comment]
Oh I am not sure. I sort of understood the idea to be to get a static version of the precious years' sites so they will always be visitable. So I think ideally it would be bsckported, especially because 2024's new features were merged into 2023 and caused the regression. On the other hand, it was not broken but just ugly. 

But it would be good to know what the policy is for older sites since I am holding back on more bug reports for 2023 😅

**Comment by hypha** [comment]
https://github.com/EuroPython/website/pull/627 fixes the issue (thanks @egeakman!)
